### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by victorokoroji** [keza681/Todo-list-project#5]

**Comment by Abenezer-Tilahun** [comment]
Great work you did. 👏 good structure& thinking process in javascript.
just one suggestion I want to add is :

- Everything looks perfect, but some  variable notation are not descriptive . Kindly make it descriptive.
- And the link to the license is not working as intended at the moment, have another look at [the template ](https://github.com/microverseinc/readme-template)provided by Microverse for an example on how it is supposed to look like.

**Comment by victorokoroji** [comment]
What a job well done 👏. You have written a clean ad DRY code. I have an optional suggestion I would recommend;

- I think you should consider using innerHTML to create  DOM elements in javascript. [38](https://github.com/keza681/Todo-list-project/blob/c890bd8d0b3f5715d107a700838a9e9c6d365729/src/index.js#L38)
